language: go
go:
- 1.10.x
script: make test
notifications:
  slack:
    secure: etzVqFK2w4SkIZx8kMXlJ5GwaLnrhmEyuE0HnRQtaktF6s7RkOf8gzdG2mgIfH1HZBrBBJecTAGTIw7gjTrjZNPtKwGz5ep/S//5Klaa+XncLkVi1qTndSu6xZ2g706ds6HG+JDGTHYhVrHC2z5pgoybISrM83TD4e8sTZOQ+0Io0s+YFjPPvTQsIetPTPEmaIhM1C1qtdrjq6qWMpfnPhTSRvSG5d8edPgn0jEKlL2J7Ghfib2S38KeTnx8Kl3uMOc7dCbL2cpNi0QS/Qh4OJSBdvit2fnkjO+RV+CvcgrQlwZlp6XUh54UARV0Lctt0jRvK3wrMY+rEmpQBw1jkApgPixmNwT26SQtqHyWJMZo3edA9wm8VrECN+wskGmZfWJffry0lkF+mzcujao2w6bpT627K/HnflQ6XnA4NFfUTWI0O/zluJwwlaNc0ADdS58vJCNHP+EhBo1XUXcCu1RtvDAwry3u2x1FiDGLlzE8zgtD+SMMGJn9wZOWnd07+dQABbJFAe7Gx0LFpEKj46jGvDE45BVoY1IMp1MpK4DpOrk0Uz8ga63LB5IqP+Or7WAyzJ8E4hO+O4wHYGXAfQ7JcbZnjLOjpHwgMKWeaoYXWRGRag5psYUy7HW8DkzmD59+0hW0Dti7bT6NnmLgrihyIKCF3TLW8FC4TvCxmSM=
